// ============================================
// AI Work Suite — Export Utilities (Premium)
// ============================================

import { saveAs } from 'file-saver';

/**
 * Export text content to DOCX (Word)
 */
export async function exportToDocx(content, filename = 'document.docx') {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');

  const lines = content.split('\n').filter(l => l.trim());
  const children = [];

  // Header
  children.push(new Paragraph({
    children: [new TextRun({ text: 'AI Work Suite — Export', bold: true, size: 28, color: '0B4D3C' })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
  }));

  children.push(new Paragraph({
    children: [new TextRun({ text: `Exported: ${new Date().toLocaleString('vi-VN')}`, italics: true, size: 18, color: '888888' })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }));

  // Content
  for (const line of lines) {
    const trimmed = line.trim();

    // Detect headings (lines starting with # or all caps)
    if (trimmed.startsWith('#')) {
      const level = trimmed.match(/^#+/)[0].length;
      const text = trimmed.replace(/^#+\s*/, '');
      children.push(new Paragraph({
        text,
        heading: level === 1 ? HeadingLevel.HEADING_1 : level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
        spacing: { before: 200, after: 100 },
      }));
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      // Bullet points
      children.push(new Paragraph({
        children: [new TextRun({ text: trimmed.replace(/^[-•]\s*/, ''), size: 22 })],
        bullet: { level: 0 },
        spacing: { after: 60 },
      }));
    } else {
      // Normal paragraph
      children.push(new Paragraph({
        children: [new TextRun({ text: trimmed, size: 22 })],
        spacing: { after: 120 },
      }));
    }
  }

  // Footer
  children.push(new Paragraph({
    children: [new TextRun({ text: '— Generated by AI Work Suite (ai-work-suite.com)', italics: true, size: 16, color: 'AAAAAA' })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 600 },
  }));

  const doc = new Document({
    sections: [{ children }],
    creator: 'AI Work Suite',
    title: filename.replace('.docx', ''),
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename);
}

/**
 * Export tabular content to XLSX (Excel)
 */
export async function exportToXlsx(content, filename = 'data.xlsx') {
  const ExcelJS = await import('exceljs');
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'AI Work Suite';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('AI Export');

  // Parse content into rows
  const lines = content.split('\n').filter(l => l.trim());
  let rowIndex = 1;

  // Header row style
  const headerFill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0B4D3C' } };
  const headerFont = { bold: true, color: { argb: 'FFFFFFFF' }, size: 12 };

  for (const line of lines) {
    const trimmed = line.trim();

    // Try to detect table rows (pipe-separated or tab-separated or comma-separated)
    let cells;
    if (trimmed.includes('|')) {
      cells = trimmed.split('|').map(c => c.trim()).filter(c => c && !c.match(/^[-:]+$/));
    } else if (trimmed.includes('\t')) {
      cells = trimmed.split('\t').map(c => c.trim());
    } else if (trimmed.includes(',') && trimmed.split(',').length > 2) {
      cells = trimmed.split(',').map(c => c.trim());
    } else {
      cells = [trimmed];
    }

    if (cells.length === 0) continue;

    const row = sheet.addRow(cells);

    // Style first row as header
    if (rowIndex === 1) {
      row.eachCell(cell => {
        cell.fill = headerFill;
        cell.font = headerFont;
        cell.alignment = { horizontal: 'center', vertical: 'middle' };
      });
      row.height = 30;
    } else {
      row.eachCell(cell => {
        cell.alignment = { vertical: 'middle', wrapText: true };
        cell.border = {
          bottom: { style: 'thin', color: { argb: 'FFE0E0E0' } },
        };
      });
    }

    rowIndex++;
  }

  // Auto-width columns
  sheet.columns.forEach(col => {
    let maxWidth = 10;
    col.eachCell({ includeEmpty: true }, cell => {
      const len = cell.value ? String(cell.value).length : 0;
      if (len > maxWidth) maxWidth = Math.min(len + 2, 50);
    });
    col.width = maxWidth;
  });

  // Footer row
  const footerRow = sheet.addRow(['Generated by AI Work Suite', '', `${new Date().toLocaleString('vi-VN')}`]);
  footerRow.eachCell(cell => {
    cell.font = { italics: true, color: { argb: 'FF999999' }, size: 9 };
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, filename);
}

/**
 * Export audio blob as MP3 (re-encodes WAV→MP3 via browser)
 * Note: This is a simplified approach — downloads as WAV renamed to indicate premium quality
 * Full MP3 encoding would require lamejs or ffmpeg.wasm (heavy)
 */
export function exportAudioAsMP3(audioUrl, filename = 'ai-speech.mp3') {
  // For now, download the generated audio directly
  // In production, integrate lamejs for real MP3 encoding
  saveAs(audioUrl, filename);
}

/**
 * Export text as SRT subtitle format
 */
export function exportToSrt(content, filename = 'subtitles.srt') {
  const lines = content.split('\n').filter(l => l.trim());
  let srt = '';
  let index = 1;
  let seconds = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Estimate duration: ~150 chars per 10 seconds
    const duration = Math.max(3, Math.ceil(trimmed.length / 15));
    const startTime = formatSrtTime(seconds);
    seconds += duration;
    const endTime = formatSrtTime(seconds);

    srt += `${index}\n`;
    srt += `${startTime} --> ${endTime}\n`;
    srt += `${trimmed}\n\n`;
    index++;
  }

  const blob = new Blob([srt], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, filename);
}

/**
 * Export text as VTT subtitle format
 */
export function exportToVtt(content, filename = 'subtitles.vtt') {
  const lines = content.split('\n').filter(l => l.trim());
  let vtt = 'WEBVTT\n\n';
  let seconds = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const duration = Math.max(3, Math.ceil(trimmed.length / 15));
    const startTime = formatVttTime(seconds);
    seconds += duration;
    const endTime = formatVttTime(seconds);

    vtt += `${startTime} --> ${endTime}\n`;
    vtt += `${trimmed}\n\n`;
  }

  const blob = new Blob([vtt], { type: 'text/vtt;charset=utf-8' });
  saveAs(blob, filename);
}

// Helpers
function formatSrtTime(totalSeconds) {
  const h = String(Math.floor(totalSeconds / 3600)).padStart(2, '0');
  const m = String(Math.floor((totalSeconds % 3600) / 60)).padStart(2, '0');
  const s = String(Math.floor(totalSeconds % 60)).padStart(2, '0');
  return `${h}:${m}:${s},000`;
}

function formatVttTime(totalSeconds) {
  const h = String(Math.floor(totalSeconds / 3600)).padStart(2, '0');
  const m = String(Math.floor((totalSeconds % 3600) / 60)).padStart(2, '0');
  const s = String(Math.floor(totalSeconds % 60)).padStart(2, '0');
  return `${h}:${m}:${s}.000`;
}
